name: Production build and deploy to S3
on:
  push:
    branches:
    - mini-calendar
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: sleavely/node-awscli:14.x
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: npm run build:widget
    - run: aws s3 sync ./build s3://footlight-widget-mini-calendar/ --acl public-read --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1 
        WEBHOSTING_BUCKET_NAME: footlight-widget-mini-calendar
    - run: aws s3 sync ./dist s3://footlight-widget-mini-calendar/dist/ --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1 
        WEBHOSTING_BUCKET_NAME: footlight-widget-mini-calendar